# Generated by Django 6.0.2 on 2026-02-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar', models.CharField(max_length=100)),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('sehir', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
